Update readme
AdguardTeam/companiesdb pull request #160
Opened 2023-03-03 15:42 UTC by jellizaveta

https://github.com/AdguardTeam/companiesdb/issues/158

2023-03-03 16:21 UTC, Alex-302 commented on README.md
> +- **tracker** - add in [source/trackers.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/trackers.json)
Callouts can be repaced by

```markdown
> **Note**
> This is a note

> **Warning**
> This is a warning
```

> **Note**
> This is a note

> **Warning**
> This is a warning

2023-03-03 18:08 UTC, Alex-302 approved these changes

2023-03-06 10:32 UTC, vbagirov requested changes

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +- **company** - add in [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json)
`add to` вместо `add in`, здесь и в следующей строке

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +> Add companies and tracker names in alphabetical order. Tracker domains - alphabetically **by value.**
`Tracker domains - alphabetically **by value.**` заменить на `Add tracker domains alphabetically **by value.**`

Ещё я не понимаю, о каком value идёт речь, предполагается, что читатель знает?

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +The data about the company is added in the [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json) file to the JSON key with the name, that defin
`is added in` → `is added to`

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +- **websiteUrl** [](https://www.notion.so/companiesdb-87733d1e43294ceb9311e6e60c1663b4)- the address of the company website, also used to define the company icon.
нет пробела после ссылки перед дефисом

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +The data about the tracker is added in the [source/trackers.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/trackers.json) file to the nested JSON key inside **trackers** se
`…to the nested JSON key inside **trackers** section with the name, that defines the **tracker name** of the company, which is used when adding trackers to the **trackerDomains** section:` → `…into the nested JSON key inside the **trackers** section with the name that defines the **tracker name** of the company, which is used when adding trackers to the **trackerDomains** section:`

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +| 4 | advertising | Provides advertising or advertising-related services such as data collection, behavioral analysis or re-targeting. |
неконсистентно — где-то есть точки в конце, где-то нет. Я бы везде убрал

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +- **dist/companies.json** - companies data json file. This file contains companies
везде `JSON`, тут `json`

2023-03-06 10:32 UTC, vbagirov commented on README.md
> +- **dist/companies.json** - companies data json file. This file contains companies
кажется, тут проблемы с переносами строки

2023-03-06 11:49 UTC, Alex-302 commented on README.md
> +- create a fork of the repository on GitHub.
Ставят
https://google.github.io/styleguide/docguide/style.html#lists

2023-03-06 11:50 UTC, Alex-302 commented on README.md
> +- [dist/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/companies.json) - contains information about companies, obtained by merging the [whotracks.me](http://whotr
```suggestion
- [dist/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/companies.json) - contains information about companies, obtained by merging the [whotracks.me](http://whotracks.me) database with [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json).
```

2023-03-06 11:52 UTC, Alex-302 commented on README.md
> +- [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json) - contains information about companies, which overwrites or supplements information in
```suggestion
- [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json) - contains information about companies, which overwrites or supplements information in [companies.json](https://github.com/AdguardTeam/companiesdb/blob/main/dist/companies.json).
```

2023-03-06 11:53 UTC, Alex-302 commented on README.md
>    to exclusions in AdGuard VPN apps. This file is composed manually and not
```suggestion
- [source/vpn_services.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/vpn_services.json) - contains a list of "Services" that can be added to exclusions in AdGuard VPN apps. This file is composed manually and not
```

2023-03-06 11:58 UTC, Alex-302 commented on README.md
>    to exclusions in AdGuard VPN apps. This file is composed manually and not
ага

2023-03-06 11:58 UTC, Alex-302 commented on README.md
>    to exclusions in AdGuard VPN apps. This file is composed manually and not
```suggestion
- [source/vpn_services.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/vpn_services.json) - contains a list of "Services" that can be added to exclusions in AdGuard VPN apps. This file is composed manually and not
```

2023-03-06 11:58 UTC, Alex-302 commented on README.md
> +If need to add new data or rewrite [whotracks.me](http://whotracks.me/) data:
```suggestion
If you need to add new data or to rewrite [whotracks.me](http://whotracks.me/) data:
```

2023-03-06 11:58 UTC, Alex-302 commented on README.md
> +- **company** - add in [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json)
```suggestion
- **company** - add to [source/companies.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/source/companies.json)
```

2023-03-06 11:58 UTC, Alex-302 commented on README.md
> +> Add companies and tracker names in alphabetical order. Tracker domains - alphabetically **by value.**
сортировка по значению ключа по алфавиту

2023-03-06 11:58 UTC, Alex-302 commented on README.md
> +> Add companies and tracker names in alphabetical order. Tracker domains - alphabetically **by value.**
```suggestion
> Add companies and tracker names in alphabetical order. Add tracker domains alphabetically **by value.**
```

2023-03-06 12:08 UTC, Alex-302 commented on README.md
> +- **websiteUrl** [](https://www.notion.so/companiesdb-87733d1e43294ceb9311e6e60c1663b4)- the address of the company website, also used to define the company icon.
```suggestion
- **websiteUrl** [](https://www.notion.so/companiesdb-87733d1e43294ceb9311e6e60c1663b4) - the address of the company website, also used to define the company icon.
```

2023-03-06 12:11 UTC, Alex-302 commented on README.md
> +The data about the tracker is added in the [source/trackers.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/trackers.json) file to the nested JSON key inside **trackers** se
```suggestion
The data about the tracker is added to the [source/trackers.json](https://raw.githubusercontent.com/AdguardTeam/companiesdb/main/dist/trackers.json) file into the nested JSON key inside the **trackers** section with the name that defines the **tracker name** of the company, which is used when adding trackers to the **trackerDomains** section:
```

2023-03-06 12:13 UTC, Alex-302 commented on README.md
> +- **dist/companies.json** - companies data json file. This file contains companies
```suggestion
- **dist/companies.json** - companies data JSON file. This file contains companies
```

2023-03-06 12:22 UTC, Alex-302 commented on README.md
> +| 4 | advertising | Provides advertising or advertising-related services such as data collection, behavioral analysis or re-targeting. |
ок

2023-03-06 12:53 UTC, Alex-302 approved these changes

2023-03-06 12:56 UTC, vbagirov approved these changes

2023-03-06 14:42 UTC, ameshkov approved these changes

2023-03-06 14:43 UTC, merged