Fix #194 Google companies/domains
AdguardTeam/companiesdb pull request #195
Opened 2023-05-26 14:02 UTC by jslawler

2023-06-13 11:41 UTC, jellizaveta requested changes

2023-06-13 11:41 UTC, jellizaveta commented on source/trackers.json
> +        "fcm.googleapis.com": "firebaseio.com",
It seems to me that the domains below are worth adding to the "firebase" tracker with the "mobile_analytics" category
"firebasedynamiclinks.googleapis.com": "firebase",
"firebasedynamiclinks-ipv4.googleapis.com": "firebase",
"firebasedynamiclinks-ipv6.googleapis.com": "firebase",
"firebaseinappmessaging.googleapis.com": "firebase"

2023-06-13 11:41 UTC, jellizaveta commented on source/trackers.json
> +        "google.com.mx": "google",
These domains are in the database: google.com.mx, google.com.au, google.com.ar

2023-06-15 10:19 UTC, jellizaveta commented on source/trackers.json
> +        "fcm.googleapis.com": "firebaseio.com",
Firebaseio itself is a mobile app development platform. 
```json
"firebaseio.com": {
    "name": "Firebase",
     /"categoryId": 8, - category "other" generally fits
    "url": "https://firebase.google.com/",
    "companyId": "google"
},
```
On the other hand most of the domains are actually used to collect user statistics

2023-06-19 09:12 UTC, jellizaveta approved these changes

2023-06-30 11:13 UTC, Alex-302 commented on source/trackers.json
> +        "firebasedynamiclinks.googleapis.com": "firebase",
Where is it used? I need a real example of use.

2023-06-30 11:13 UTC, Alex-302 commented on source/trackers.json
> +        "g.co": "google",
It is not used anymore.

2023-06-30 11:18 UTC, Alex-302 commented on source/trackers.json
> +        "firebasedynamiclinks.googleapis.com": "firebase",
It is not worth adding domains that are not in use. Because of this, the database will contain a lot of irrelevant information.

2023-06-30 11:25 UTC, Alex-302 commented on source/trackers.json
> +        "g.co": "google",
I am aware of most of these domains.

2023-06-30 11:25 UTC, Alex-302 commented on source/trackers.json
> +        "firebasedynamiclinks.googleapis.com": "firebase",
I am aware of most of these domains.

2023-06-30 11:26 UTC, Alex-302 commented on source/trackers.json
> +        "g.co": "google",
g.co/yourfamily
it seems used

2023-06-30 11:26 UTC, Alex-302 approved these changes

2023-06-30 12:05 UTC, jellizaveta approved these changes

2023-06-30 12:06 UTC, merged