Add isolarcloud.com #210
AdguardTeam/companiesdb pull request #211
Opened 2023-06-07 14:42 UTC by jslawler

2023-06-13 12:38 UTC, jellizaveta requested changes

2023-06-13 12:38 UTC, jellizaveta commented on source/companies.json
> +        "isolarcloud": {
Maybe `Sungrow Power Supply Company Limited` could be added to the company and as a product `isolarcloud` to the trackers

2023-06-15 11:15 UTC, Alex-302 commented on source/companies.json
> +            "description": "Sungrow is the world’s most bankable inverter brand with over 340 GW installed worldwide as of December 2022. Founded in 1997 by University Professor Cao Renxian, Sungrow
Is not it too long? Description is not a biography of a company:)

2023-06-19 09:12 UTC, jellizaveta approved these changes

2023-06-20 11:36 UTC, Alex-302 approved these changes

2023-06-26 10:37 UTC, jellizaveta commented
@jslawler Could you pull the current master in your branch, because changes were made in the repository and workflows modified.

2023-06-26 10:40 UTC, ghost commented
> @jslawler Could you pull the current master in your branch, because changes were made in the repository and workflows modified.

Done

2023-06-26 10:41 UTC, merged

2023-06-26 10:43 UTC, jellizaveta commented
Can I ask you to do the same for the other prs to pass the checks properly?

2023-06-26 10:46 UTC, ghost commented
> Can I ask you to do the same for the other prs to pass the checks properly?

They all should be done now.