Fix #218 msidentity.com
AdguardTeam/companiesdb pull request #219
Opened 2023-06-12 22:55 UTC by jslawler

2023-06-13 12:51 UTC, jellizaveta approved these changes

2023-06-15 11:01 UTC, Alex-302 requested changes

2023-06-15 11:01 UTC, Alex-302 commented on source/trackers.json
> +        "msidentity.com": "microsoft",
sort by value=>key_name

2023-06-19 09:11 UTC, jellizaveta approved these changes

2023-06-20 11:48 UTC, Alex-302 approved these changes

2023-06-26 10:45 UTC, merged