Fix #200 foxtel
AdguardTeam/companiesdb pull request #224
Opened 2023-06-15 20:33 UTC by jslawler

#200

2023-06-19 09:17 UTC, jellizaveta requested changes

2023-06-19 09:17 UTC, jellizaveta commented on source/trackers.json
> +            "description": "Binge is a video streaming subscription service available in Australia, owned by Streamotion (a wholly owned subsidiary of Foxtel). The service offers on demand and live e
```json
  "binge": {
    "name": "Binge",
    "categoryId": 0,
    "url": "https://binge.com.au/",
    "companyId": "foxtel"
    },

2023-06-26 10:23 UTC, jellizaveta approved these changes

2023-06-30 11:01 UTC, Alex-302 approved these changes

2023-06-30 11:01 UTC, merged