Add company FarLight Pte Ltd.
AdguardTeam/companiesdb pull request #236
Opened 2023-07-03 04:24 UTC by jslawler

FarLight Games is the publisher for Lilith Games, publishing many major titles on current mobile app stores.

2023-07-04 14:38 UTC, jellizaveta requested changes

2023-07-04 14:38 UTC, jellizaveta commented on source/trackers.json
> +        "farlight_pte_ltd.": {
Does this tracker have domains?

2023-07-13 15:42 UTC, jellizaveta requested changes

2023-07-13 15:42 UTC, jellizaveta commented on source/trackers.json
> +        "farlight_pte_ltd.": {
I think we can write it without the point `farlight_pte_ltd.  --> farlight_pte_ltd`

2023-07-26 11:40 UTC, Alex-302 approved these changes

2023-07-26 12:21 UTC, jellizaveta approved these changes

2023-07-31 08:53 UTC, merged