Fix #266 Add more Disney data
AdguardTeam/companiesdb pull request #269
Opened 2023-10-06 00:37 UTC by jslawler

- Correct Disney company description
- Add VOD provider Disney Streaming, which was originally BAMtech, until purchased by Disney
- Add streaming service Disney+

2023-10-06 15:05 UTC, jellizaveta requested changes

2023-10-06 15:05 UTC, jellizaveta commented on source/trackers.json
> +            "categoryId": 8,
Why not  `"0": "audio_video_player"` category?

2023-10-09 17:35 UTC, jellizaveta requested changes
dssott.com - looks like Disney Plus
dssedge.com - can't find information about this domain

2023-10-09 18:57 UTC, ghost commented
The dss part of the domains stands for Disney Streaming Services. 

Whilst used for Disney+, Disney Streaming Services is a company in itself which provides the VOD component for many other Walt Disney companies as well.

2023-10-10 10:29 UTC, jellizaveta approved these changes

2023-10-11 15:29 UTC, Alex-302 approved these changes

2023-10-11 15:31 UTC, Alex-302 approved these changes

2023-10-11 15:31 UTC, merged