pki.goog
AdguardTeam/companiesdb pull request #27
Opened 2023-01-30 11:54 UTC by jellizaveta

https://github.com/AdguardTeam/companiesdb/issues/20

2023-01-30 15:14 UTC, Alex-302 approved these changes

2023-01-30 20:53 UTC, ameshkov requested changes

2023-01-30 20:53 UTC, ameshkov commented on dist/adguard.json
> +            "categoryId": 6,
```suggestion
            "categoryId": 5,
```

This should be `"5": "essential",`, not analytics

2023-02-01 13:17 UTC, ameshkov approved these changes

2023-02-01 14:41 UTC, merged