hotmail.com
AdguardTeam/companiesdb pull request #28
Opened 2023-01-30 12:17 UTC by jellizaveta

https://github.com/AdguardTeam/companiesdb/issues/22

2023-01-30 16:33 UTC, Alex-302 approved these changes

2023-01-30 20:51 UTC, ameshkov requested changes

2023-01-30 20:51 UTC, ameshkov commented on dist/adguard.json
> +            "categoryId": 10,
```suggestion
            "categoryId": 13,
```

Category should be `13` -- Email

2023-02-01 13:17 UTC, ameshkov approved these changes

2023-02-01 14:44 UTC, merged