add aiv-delivery.net
AdguardTeam/companiesdb pull request #299
Opened 2023-10-29 05:07 UTC by kyjhoz-mikfip-goXci0

2023-11-01 15:59 UTC, jellizaveta requested changes

2023-11-01 15:59 UTC, jellizaveta commented on source/trackers.json
> +        "aiv-delivery.net": "amazon",
could be in separate tracker `Amazon Video`:
```
"amazon_video": {
            "name": "Amazon Video",
            "categoryId": 0,
            "url": "https://www.primevideo.com/",
            "companyId": "amazon"
        },
```

```
"aiv-delivery.net": "amazon_video",
"aiv-cdn.net": "amazon_video",
"amazonvideo.com": "amazon_video",
"primevideo.com": "amazon_video",

```

2023-11-09 12:32 UTC, jellizaveta approved these changes

2023-11-09 13:44 UTC, Alex-302 approved these changes

2023-11-09 13:44 UTC, merged