added companies table
AdguardTeam/companiesdb pull request #3
Opened 2022-04-12 11:30 UTC by Mizzick

2022-04-12 16:16 UTC, ameshkov requested changes

2022-04-13 09:25 UTC, Mizzick commented on dist/adguard_companies.json
> +    "companies": {
Here I've collected companies used in adguard.json.
Although this list should be reviewed.

2022-04-13 09:31 UTC, ameshkov requested changes

2022-04-13 09:31 UTC, ameshkov commented on README.md
> +- `whotrackme_companies.json`
Do we really need this one? Seems to be a temporary result that will be then merged into `companies.json`.

Also, `adguard.json` is both a source and an output

2022-04-13 14:40 UTC, ameshkov approved these changes

2022-04-13 14:40 UTC, merged