add pv-cdn.net
AdguardTeam/companiesdb pull request #301
Opened 2023-10-29 05:07 UTC by kyjhoz-mikfip-goXci0

2023-11-01 16:01 UTC, jellizaveta requested changes

2023-11-01 16:01 UTC, jellizaveta commented on source/trackers.json
> +        "pv-cdn.net": "amazon",
could be in Amazon Video as well 
https://github.com/AdguardTeam/companiesdb/pull/299#discussion_r1378993742

2023-11-09 12:32 UTC, jellizaveta approved these changes

2023-11-09 13:46 UTC, Alex-302 approved these changes

2023-11-09 13:46 UTC, merged