add dependabot
AdguardTeam/companiesdb pull request #317
Opened 2023-10-29 12:18 UTC by kyjhoz-mikfip-goXci0

PR to add Dependabot, to keep Yarn (npm) and GitHub Actions updated.

Consider turning on Dependabot alerts, security updates, and version updates.

2023-11-09 13:17 UTC, jellizaveta requested changes

2023-11-09 13:17 UTC, jellizaveta commented on .github/dependabot.yml
> +      interval: "daily"
Recommended to have empty line in the end of a yml file

2023-11-10 13:38 UTC, jellizaveta approved these changes

2023-11-24 12:49 UTC, Alex-302 approved these changes

2023-12-01 13:53 UTC, merged