Fix alibaba trading name
AdguardTeam/companiesdb pull request #318
Opened 2023-11-02 06:28 UTC by kyjhoz-mikfip-goXci0

Alibaba is owned by SoftBank Group Corp, see top 5 shareholders [here](https://www.investopedia.com/articles/investing/111114/top-five-alibaba-shareholders.asp).

2023-11-09 13:07 UTC, jellizaveta requested changes

2023-11-09 13:07 UTC, jellizaveta commented on source/trackers.json
> +            "url": "http://www.adchina.com/",
cannot find this website

2023-11-09 13:07 UTC, jellizaveta commented on source/trackers.json
> +            "url": "https://www.alipay.com/",
`https://global.alipay.com/`

2023-11-10 13:49 UTC, jellizaveta approved these changes

2023-11-24 12:54 UTC, Alex-302 approved these changes

2023-11-24 12:59 UTC, Alex-302 approved these changes

2023-11-24 12:59 UTC, merged