Fix #44
AdguardTeam/companiesdb pull request #45
Opened 2023-02-03 08:01 UTC by jslawler

Also correct registered trademark: https://trademarks.justia.com/owners/reddit-inc-2512865/

2023-02-03 18:33 UTC, jellizaveta requested changes

2023-02-03 18:33 UTC, jellizaveta commented on dist/companies.json
> +            "websiteUrl": "www.reddit.com",
full website address: `https://www.reddit.com/`
file for changes: `adguard_companies.json`

2023-02-04 14:43 UTC, ameshkov requested changes
The changes should only be made to `adguard_companies.json`

2023-02-05 20:52 UTC, Alex-302 commented on dist/adguard_companies.json
> +            "description": "\\\"reddit is a source for what's new and popular on the web. Users like you provide all of the content and decide, through voting, what's good and what's junk.\\\""
Is `\\\"` necessary?

2023-02-06 15:25 UTC, ameshkov approved these changes

2023-02-06 15:25 UTC, ameshkov commented on dist/adguard_companies.json
> +            "description": "\\\"reddit is a source for what's new and popular on the web. Users like you provide all of the content and decide, through voting, what's good and what's junk.\\\""
comes from whotracksme db

2023-02-07 09:12 UTC, jellizaveta approved these changes

2023-02-08 08:51 UTC, merged