Added AdGuard domains
AdguardTeam/companiesdb pull request #48
Opened 2023-02-03 20:44 UTC by Alex-302

https://github.com/AdguardTeam/companiesdb/issues/21

2023-02-04 14:37 UTC, ameshkov requested changes
We shouldn't change `whotracksme.json`, it's readonly.

If you want to override anything, add it to `adguard*.json` files.

2023-02-06 12:04 UTC, jellizaveta requested changes
I think we should add company data

2023-02-06 12:56 UTC, jellizaveta approved these changes

2023-02-06 13:04 UTC, jellizaveta commented
Should there be a different title for each product?  (VPN, DNS, AdBlocker)

2023-02-06 14:41 UTC, ameshkov approved these changes

2023-02-06 14:41 UTC, merged