fix #6: mailru group company
AdguardTeam/companiesdb pull request #8
Opened 2022-08-08 19:02 UTC by Mizzick

upd mailru group company

2022-08-08 20:57 UTC, Alex-302 commented on dist/adguard.json
> +            "url": "http://mail.ru/",
Здесь не `ad.mail.ru` должен быть?

2022-08-08 20:57 UTC, Alex-302 commented on dist/adguard.json
> +            "url": "http://mail.ru/",
Для счётчиков у них другие домены
```
||mediator.mail.ru^$third-party
||top-staging.mail.ru^
||1l-hit.mail.ru^
||mediator.imgsmail.ru^
||stat.radar.imgsmail.ru^
||top-fwz1.mail.ru^
||xray.mail.ru^
||rs.mail.ru^$domain=~account.mail.ru
||trk.mail.ru^$image,ping
||top.mail.ru/counter$third-party
||r0.mail.ru/pixel/
```

2022-08-09 06:19 UTC, ameshkov requested changes
А собери всю базу - непонятно какие изменения действительно вносит этот PR в финальную базу

2022-08-09 06:19 UTC, ameshkov commented on dist/adguard.json
> +            "url": "http://mail.ru/",
Это просто сайт компании

2022-08-09 06:46 UTC, Mizzick commented on dist/adguard.json
> +            "url": "http://mail.ru/",
если нужно их можно добавить вот сюда
https://github.com/AdguardTeam/companiesdb/blob/main/dist/adguard.json#L130

сейчас есть только вот эти
https://github.com/AdguardTeam/companiesdb/blob/main/dist/whotracksme.json#L21593

2022-08-09 06:51 UTC, Mizzick commented
> А собери всю базу - непонятно какие изменения действительно вносит этот PR в финальную базу

 изменения только в adguard.json

2022-08-09 07:03 UTC, ameshkov approved these changes

2022-08-09 09:03 UTC, Alex-302 approved these changes

2022-08-09 09:10 UTC, merged