Fix #97 whatsapp.net
AdguardTeam/companiesdb pull request #98
Opened 2023-02-17 17:32 UTC by jellizaveta

https://github.com/AdguardTeam/companiesdb/issues/97

2023-02-20 12:53 UTC, ameshkov approved these changes

2023-02-20 13:00 UTC, Alex-302 commented
@jellizaveta @ameshkov Maybe `Meta` should be used as `companyId` for their services?

2023-02-20 15:22 UTC, ameshkov commented
@Alex-302 you're completely right.

2023-02-20 15:22 UTC, ameshkov requested changes
WhatsApp belongs to Meta

2023-02-21 06:21 UTC, zloyden approved these changes

2023-02-21 06:58 UTC, Alex-302 approved these changes

2023-02-21 06:58 UTC, merged